#!/usr/bin/bash

# exit on error
set -e

# print usage
if [ $# -le 1 ]; then
    echo "Usage: generate_isrs.sh <isrs_gen.cpp> <isrs_gen.inc>"
    exit 1
fi

# vars
ISRS_GEN_C=$1
ISRS_GEN_ASM=$2

ISRS_WITH_ERROR_CODE="8 10 11 12 13 14 17 21"


#
# Generate C file
#
echo "// !!! THIS FILE IS AUTOGENERATED !!!" > $ISRS_GEN_C
echo "#include <core/arch/i686/IDT.hpp>" >> $ISRS_GEN_C
echo "#include <core/arch/i686/GDT.hpp>" >> $ISRS_GEN_C
echo "using namespace arch::i686;" >> $ISRS_GEN_C
echo "" >> $ISRS_GEN_C

for i in $(seq 0 255); do
    echo "EXPORT void ASMCALL ISRWrapper${i}();" >> $ISRS_GEN_C
done

echo "" >> $ISRS_GEN_C
echo "EXPORT void ISR_Initialize() {" >> $ISRS_GEN_C

for i in $(seq 0 255); do
    echo "    IDT::SetGate(${i}, (void*)ISRWrapper${i}, GDT::CodeSegment, IDT::FLAG_RING0 | IDT::FLAG_GATE_32BIT_INT);" >> $ISRS_GEN_C
done


echo "}" >> $ISRS_GEN_C

#
# Generate assembly file
#
echo "; !!! THIS FILE IS AUTOGENERATED !!!" > $ISRS_GEN_ASM

for i in $(seq 0 255); do
    if echo "$ISRS_WITH_ERROR_CODE" | grep -q "\b${i}\b"; then
        echo "ISR_ERRORCODE ${i}" >> $ISRS_GEN_ASM
    else
        echo "ISR_NOERRORCODE ${i}" >> $ISRS_GEN_ASM
    fi
done